services:
  holocron:
    image: helloseam/holocron:latest
    build: .
    privileged: true
    environment:
      - HOLOCRON_ARCH=${HOLOCRON_ARCH:-}
      - HOLOCRON_VARIANT=${HOLOCRON_VARIANT:-}
      - OSTREE_REPO=${OSTREE_REPO:-/tmp/holocron-ostree}
    tmpfs:
      - /tmp
      - /var/lib/containers/storage
    volumes:
      - ${HOME}/.docker:/root/.docker
      - ${OSTREE_REPO:-/tmp/holocron-ostree}:${OSTREE_REPO:-/tmp/holocron-ostree}
