services:
  holocron:
    image: helloseam/holocron:latest
    build: .
    privileged: true
    environment:
      - OSTREE_REPO=${OSTREE_REPO:-/tmp/holocron-ostree}
    volumes:
      - storage:/var/lib/containers/storage
      - ${OSTREE_REPO:-/tmp/holocron-ostree}:${OSTREE_REPO:-/tmp/holocron-ostree}

volumes:
  storage:
