on:
  workflow_dispatch:
    inputs:
      container_tag:
        description: Tag for container
        default: "latest"
        required: true

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

name: Publish container

env:
  CONTAINER_NAME: helloseam/holocron:${{ github.event.inputs.container_tag || github.event.pull_request.head.ref || 'latest' }}
  DOCKER_BUILDKIT: "1"
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  publish:
    name: Build and publish image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and push container
        run: |
          build_args=(
            --push --pull
            --build-arg BUILDKIT_INLINE_CACHE=1
            --tag "$CONTAINER_NAME"
          )

          if docker pull "$CONTAINER_NAME"; then
            build_args+=(--cache-from "$CONTAINER_NAME")
          fi

          if docker pull "helloseam/holocron:latest"; then
            build_args+=(--cache-from "helloseam/holocron:latest")
          fi

          docker buildx build "${build_args[@]}" .
